apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-uug4
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0030-tenant/tkrw-pr712-0075-0030-app/devfile-sample-uug4@sha256:e479685084e6f98880bc971668ba9ffa37aeb6078d11713e54cbc3496da3b668
        name: my-nodejs
        resources: {}
status: {}
